<?xml version="1.0"?>
<!DOCTYPE pargres [
 <!ELEMENT pargres (users,cluster,metadata,sort)>
 <!ELEMENT users (user*)>
 <!ELEMENT user EMPTY>
 <!ATTLIST user name CDATA #REQUIRED>		
 <!ATTLIST user password CDATA #REQUIRED>	
 <!ELEMENT cluster (node*)> 
 <!ELEMENT node EMPTY>
 <!ATTLIST node host CDATA #REQUIRED>	
 <!ATTLIST node port CDATA #REQUIRED>	 
 <!ELEMENT metadata (vp*)> 
 <!ELEMENT vp EMPTY> 
 <!ATTLIST vp table CDATA #REQUIRED>	
 <!ATTLIST vp field CDATA #REQUIRED>			
]>

<pargres>
	<users>
		<user name="user" password=""/>
	</users>
	<cluster>
		<node host="node9" port="3001"/>
		<node host="node12" port="3001"/>
		<node host="node13" port="3001"/>
		<node host="node15" port="3001"/>
		<node host="node16" port="3001"/>						
	</cluster>
	<metadata>
		<vp table="lineitem" field="l_orderkey"/>
		<vp table="orders" field="o_orderkey"/>
	</metadata>
		<metadata>
		<vp table="lineitem" field="l_orderkey"/>
		<vp table="orders" field="o_orderkey"/>
	</metadata>
	
</pargres>